version: '3.8'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
    command: bash -c "litestar --app app.app:app run --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network


  migrations:
    build: .
    depends_on:
      - db
    command: bash -c "yes | litestar database upgrade"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network


volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
